version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "push"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "https://github.com/AnkitSuryavanshi/DockerExample"
    # Clone the master branch. Or, use ${{CF_BRANCH}} to get branch name from trigger
    # Learn more at https://codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "main"
    stage: "clone"
    
  Freestyle:
    title: Running FreeStyle image
    type: freestyle
    working_directory: '${{clone}}'
    image: alpine:latest
    commands:
      - pwd    
      - ls
    stage: "clone"
    
    
  build_my_app:
    title: Building Node.Js Docker Image
    type: build
    stage: build
    image_name: surya1206/my-node-js-app
    working_directory: '${{clone}}'
    tag: 'master'
    dockerfile: Dockerfile
    registry: LocalDockerHub
    
  push_to_my_registry:
    stage: 'push'
    type: push
    title: Pushing to a registry
    candidate: ${{build_my_app}}
    tag: 'v1.0.0'
    registry: LocalDockerHub
    image_name: surya1206/my-node-js-app-1